### ISSUE TITLE
Error [Makefile:234: __sub-make]

### ISSUE THREAD

**Issue by docfufu** [Szybet/tuxedo-kernel-aur#1]
When trying to start process with makepkg -s -i --skipinteg -f, it gaves me errors with actual version of Tuxedo kernel 6.5-6.5.0-10042.46 .
This errors occur 
no rule exists to create the target "/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/stdbool.h", required by "/home/docfufu/tuxedo-kernel-aur/s
rc/tuxedocomputers/tools/bpf/resolve_btfids/libsubcmd/exec-cmd.o".  

No rule exists to create the target "/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/stdbool.h", required by "/home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/objtool/libsubcmd/exec-cmd.o".  

Is this error related to the tuxedo-kernel-aur or with the Tuxedo sources itself ?

**Comment by Szybet** [comment]
tuxedo sources, but more strictly you are missing something on your system, a package

Idk, I will soon update my machine, I will give you feedback about it

don't go complain to tuxedo, they have better things to do

**Comment by Szybet** [comment]
Worked for me. I don't know, you might be missing something on your system? Do a full update, make sure you have `base-devel` package.

**Comment by docfufu** [comment]
Still same error, base-devel is installed,core/base-devel 1-1 (2.0 KiB 0.0 B) (Installiert), running full uodate before.
I am using EndeavorOS if this makes any diference

=> Beginne build()...
  SYNC    include/config/auto.conf
  DESCEND objtool
  DESCEND bpf/resolve_btfids
make[4]: „install_headers“ ist bereits aktuell.
make[4]: „install_headers“ ist bereits aktuell.
make[5]: *** Keine Regel vorhanden, um das Ziel „/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/stdbool.h“, benötigt von „/home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/bpf/resolve_btfids/libsubcmd/exec-cmd.o“, zu erstellen.  Schluss.
make[4]: *** [Makefile:80: /home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/bpf/resolve_btfids/libsubcmd/libsubcmd-in.o] Fehler 2
make[3]: *** [Makefile:58: /home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/bpf/resolve_btfids//libsubcmd/libsubcmd.a] Fehler 2
make[2]: *** [Makefile:76: bpf/resolve_btfids] Fehler 2
make[1]: *** [/home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/Makefile:1445: tools/bpf/resolve_btfids] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet …
make[5]: *** Keine Regel vorhanden, um das Ziel „/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/stdbool.h“, benötigt von „/home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/objtool/libsubcmd/exec-cmd.o“, zu erstellen.  Schluss.
make[4]: *** [Makefile:80: /home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/objtool/libsubcmd/libsubcmd-in.o] Fehler 2
make[3]: *** [Makefile:78: /home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/tools/objtool/libsubcmd/libsubcmd.a] Fehler 2
make[2]: *** [Makefile:73: objtool] Fehler 2
make[1]: *** [/home/docfufu/tuxedo-kernel-aur/src/tuxedocomputers/Makefile:1445: tools/objtool] Fehler 2
make: *** [Makefile:234: __sub-make] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

**Comment by Szybet** [comment]
You are outdated somehow, i have `/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include/stdbool.h`

**Comment by docfufu** [comment]
Can you point me in a direction to solve this ?

**Comment by Szybet** [comment]
update your system i ques? `sudo pacman -Syu`

**Comment by docfufu** [comment]
This was not the issue, system was fully updated before trying to build. I renamed the original tuxedo_Aur folder and started from scratch. Now the build process works normal as before.No clue what the real issue was, anyway thank you very much for providing this Repo and your help

**Comment by Szybet** [comment]
It was not as our gcc version didn't match. Anyway whatever

No problem
